In [6]:
%pip install torchvision

Note: you may need to restart the kernel to use updated packages.


In [99]:
import numpy as np
from torchvision.datasets import MNIST
def download_mnist(is_train: bool):
    dataset = MNIST(root='./data1',
        transform=lambda x: np.array(x).flatten(),
        download=True,
        train=is_train)
    
    mnist_data = []
    mnist_labels = []
    
    for image, label in dataset:
        mnist_data.append(image)
        mnist_labels.append(label)
        
    return mnist_data, mnist_labels
    
i_train_X, i_train_Y = download_mnist(True)
i_test_X, i_test_Y = download_mnist(False)

In [3]:
# print(train_Y)

In [6]:
def convert_to_one_hot_encoding(labels: np.ndarray) -> np.ndarray:
    return np.eye(10)[labels]

In [7]:
train_Y_one_hot_encoding = convert_to_one_hot_encoding(train_Y)
# print(train_Y_one_hot_encoding)

test_Y_one_hot_encoding = convert_to_one_hot_encoding(test_Y)
# print(test_Y_one_hot_encoding)

In [8]:
print(type(train_Y_one_hot_encoding))
print(type(test_Y_one_hot_encoding))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [16]:
print(type(train_X))
train_X = np.array(train_X)
test_X = np.array(test_X)
print(type(train_X))
print(type(train_X[0]))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
import numpy as np
w = np.random.uniform(low=0, high=1, size=(784, 10))
b = np.random.uniform(low=0, high=1, size=(10, ))
print(type(w))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [18]:
m = 13
batch = train_X[:m, :]
print(type(train_X))
print(type(batch))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [21]:
def normalized(input: np.ndarray) -> np.ndarray:
    return input / 255

batch = normalized(batch)
batch

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
# x = np.random.uniform(low=0, high=1, size=(1, 784))
x = batch
print(w.shape)
print(x.shape)
print(b.shape)

(784, 10)
(13, 784)
(10,)


In [30]:
z = x @ w + b

In [31]:
print(z.shape)

(13, 10)


In [43]:
def softmax(z: np.ndarray) -> np.ndarray:
    e_z = np.exp(z)
    return e_z / e_z.sum(axis = 1, keepdims = True)

In [44]:
y = softmax(z)

In [45]:
print(y)

[[1.68400402e-01 1.09746053e-02 4.97885344e-06 7.62408791e-01
  4.73095799e-02 4.09245518e-03 3.39132317e-03 5.48319965e-04
  1.99311629e-03 8.76428068e-04]
 [9.10747636e-05 1.38529449e-04 1.79412808e-07 9.87474528e-01
  1.17005877e-03 1.54460922e-03 5.39887365e-05 6.06970639e-05
  2.66492717e-04 9.19984137e-03]
 [2.70318438e-03 2.02068469e-01 1.00174262e-02 3.16253033e-01
  1.09522355e-02 1.19517195e-01 1.00323431e-01 1.00547101e-03
  2.26919140e-03 2.34890364e-01]
 [2.19224544e-01 1.08829128e-02 6.44532616e-03 3.89274038e-01
  1.46054309e-01 2.87720511e-02 1.11006615e-01 1.23275415e-02
  6.08731593e-03 6.99253472e-02]
 [4.72416464e-04 1.76567840e-04 1.23204838e-06 2.50631817e-03
  8.25239025e-04 3.12873019e-03 9.23028510e-01 6.27864627e-02
  4.84272891e-03 2.23179498e-03]
 [1.19964234e-02 4.39249164e-03 3.07874734e-04 1.77955587e-01
  1.26756566e-02 2.17148809e-03 7.57935764e-01 3.13019699e-03
  2.35972294e-03 2.70747945e-02]
 [1.78130017e-02 4.16449282e-02 3.69216889e-05 5.64119492e

In [50]:
y_ = np.argmax(y, axis = 1)

In [51]:
print(y_)

[3 3 3 3 6 6 4 3 4 6 1 4 4]


In [52]:
def cross_entropy(y_, y):
    return - np.sum(y * np.log(y_))

In [57]:
y_batch = train_Y[:m]
loss = cross_entropy(y_, y_batch)
print(loss)

-55.02129540230514


In [65]:
print(w)
print(b)

[[0.22572476 0.351076   0.9437021  ... 0.432876   0.07582175 0.09293933]
 [0.87466644 0.5925958  0.24762545 ... 0.18826031 0.0287874  0.02688922]
 [0.03389935 0.32942256 0.54800663 ... 0.7971835  0.85789229 0.43592229]
 ...
 [0.82521186 0.92878306 0.52432488 ... 0.7580914  0.85688651 0.38979159]
 [0.78555454 0.17710324 0.94085198 ... 0.08200829 0.46392864 0.67269786]
 [0.15480996 0.50062253 0.40169843 ... 0.56226995 0.36706065 0.16528863]]
[0.52072366 0.6243422  0.03410834 0.99313061 0.92171819 0.3251874
 0.1307649  0.6744717  0.27857279 0.36613341]


In [73]:
def back_propagation_gradient_descent(w, b, x, y_label, y_prediction):
    miu = 0.1
    gradient = y_label - y_prediction
    # w = w + miu * (x.T @ gradient)
    # b = b + miu * gradient

    print(x.T.shape)
    print(gradient.shape)
    
    w_add = x.T @ gradient
    # b_add = np.array(gradient, dtype = np.float64)
    b_add = gradient.sum(axis = 0)

    w_add *= miu
    b_add *= miu

    print(w.shape)
    print(w_add.shape)
    
    w += w_add
    b += b_add
    
    return w, b

In [74]:
w1, b1 = back_propagation_gradient_descent(w, b, x, convert_to_one_hot_encoding(y_batch), convert_to_one_hot_encoding(y_))

(784, 13)
(13, 10)
(784, 10)
(784, 10)


In [ ]:
-------------------------------------Final Solution-------------------------------------------------

In [86]:
def convert_to_one_hot_encoding(labels: np.ndarray) -> np.ndarray:
    return np.eye(10)[labels]

def normalized(input: np.ndarray) -> np.ndarray:
    return input / 255

In [87]:
def transform_initial_data(train_X, train_Y, test_X, test_Y):
    train_Y = convert_to_one_hot_encoding(train_Y)
    test_Y = convert_to_one_hot_encoding(test_Y)
    
    train_X = np.array(train_X)
    test_X = np.array(test_X)

    train_X = normalized(train_X)
    test_X = normalized(test_X)
    
    return train_X, train_Y, test_X, test_Y

In [88]:
def softmax(z: np.ndarray) -> np.ndarray:
    e_z = np.exp(z)
    return e_z / e_z.sum(axis = 1, keepdims = True)

In [89]:
def forward_propagation(x, w, b):
    z = x @ w + b
    y = softmax(z)
    return y

In [90]:
def predict(y):
    y = np.argmax(y, axis = 1)
    y = convert_to_one_hot_encoding(y)
    return y

In [91]:
def cross_entropy(predicition_Y, train_Y):
    return - np.sum(train_Y * np.log(predicition_Y))

In [126]:
def back_propagation(train_X, w, b, predicition_Y, train_Y, miu=0.2):
    gradient = train_Y - predicition_Y
    w = w + miu * (train_X.T @ gradient)
    b = b + miu * gradient.sum(axis = 0)
    return w, b

In [94]:
def train_neural_network(train_X, train_Y, epoch_count, m=100):
    w = np.random.uniform(low=0, high=1, size=(784, 10))
    b = np.random.uniform(low=0, high=1, size=(10, ))

    train_count = train_X.shape[0]

    for i in range(0, epoch_count):
        indices = np.arange(0, train_count)
        np.random.shuffle(indices)

        train_X = train_X[indices]
        train_Y = train_Y[indices]

        for j in range(0, train_count, m):
            batch_X = train_X[j:j+m]
            batch_Y = train_Y[j:j+m]

            fp = forward_propagation(batch_X, w, b)
            
            predictions = predict(fp)

            # cross_entropy_loss = cross_entropy(predictions, batch_Y)

            w, b = back_propagation(batch_X, w, b, predictions, batch_Y)

    return w, b     

In [128]:
def test_neural_network(test_X, w, b, test_Y):
    fp = forward_propagation(test_X, w, b)
    predictions = predict(fp)

    print(f"{predictions.shape=}; {test_Y.shape=}")

    # test_count = test_Y.shape[0]
    # accuracy = 0
    # for i in range(0, test_count):
    #     accuracy += predictions[i] @ test_Y[i]
    # accuracy = accuracy / test_count

    accuracy = np.mean(np.sum(predictions * test_Y, axis=1))

    return accuracy

In [131]:
train_X, train_Y, test_X, test_Y = transform_initial_data(i_train_X, i_train_Y, i_test_X, i_test_Y)
epoch_count = 50

accuracy = 0
while accuracy<0.9:
    w, b = train_neural_network(train_X, train_Y, epoch_count)
    accuracy = test_neural_network(test_X, w, b, test_Y)
    print(accuracy)
print(f"final accuracy = {accuracy}")

predictions.shape=(10000, 10); test_Y.shape=(10000, 10)
0.9089
final accuracy = 0.9089
